# Generated by Django 2.2.3 on 2019-07-24 21:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('privacy_mode', models.CharField(choices=[('link', 'link')], max_length=10)),
                ('invite_token', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='LunchSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'monday'), (1, 'tuesday'), (2, 'wednesday'), (3, 'thursday'), (4, 'friday'), (5, 'saturday'), (6, 'sunday')])),
                ('confirm_delta', models.PositiveSmallIntegerField(default=2, help_text='We will send confirmation request specified number of days before lunch. We send all messages around 10:00 AM.', validators=[django.core.validators.MaxValueValidator(6)])),
                ('confirm_timeout', models.PositiveSmallIntegerField(default=24, help_text='User will have specified amount of hours to confirm request. After that time request will be declined automatically.\nAt least one day should remain before lunch.', validators=[django.core.validators.MaxValueValidator(144)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_schedules', to='core.Company')),
            ],
            options={
                'verbose_name': 'lunch schedule',
                'verbose_name_plural': 'lunch schedules',
                'unique_together': {('company', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField()),
                ('confirmations_created_at', models.DateTimeField(blank=True, null=True)),
                ('auto_decline_after', models.DateTimeField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunches', to='core.LunchSchedule')),
            ],
            options={
                'verbose_name': 'lunch',
                'verbose_name_plural': 'lunches',
                'unique_together': {('schedule', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default='online', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'unique_together': {('company', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ConfirmationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('new', 'new'), ('delivered', 'delivered'), ('confirmed', 'confirmed'), ('declined', 'declined'), ('auto declined', 'auto declined')], default='new', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_requests', to='core.Employee')),
                ('lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_requests', to='core.Lunch')),
            ],
            options={
                'verbose_name': 'confirmation request',
                'verbose_name_plural': 'confirmation requests',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(related_name='companies', through='core.Employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
