# Generated by Django 2.2.3 on 2019-08-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchgroupmember',
            name='notification_message_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lunchgroupmember',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
