# Generated by Django 2.2.3 on 2019-07-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190721_2124'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Lunch',
        ),
    ]
