# Generated by Django 2.2.4 on 2019-12-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_telegramchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='lunches_enabled',
            field=models.BooleanField(default=True, verbose_name='lunches enabled'),
        ),
    ]
